permissions:
  contents: write

name: Update NASA APOD

on:
  schedule:
    - cron: '0 3 * * *'  # ë§¤ì¼ ì˜¤ì „ 3ì‹œ UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run APOD script
      env:
        NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      run: |
        echo "Replacing API Key..."
        sed -i "s/YOUR_NASA_API_KEY/$NASA_API_KEY/" update_apod.py
        python update_apod.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull --rebase origin main  # ğŸ”¥ ìµœì‹  ìƒíƒœë¡œ ë§ì¶˜ í›„
        git add README.md
        git commit -m "NASA APOD ìë™ ì—…ë°ì´íŠ¸" || echo "No changes"
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rydbfk/today_nasa.git

